l2_db: <l2_name>
l3_db: <l3_name>
etl_start_date: yyyy-mm-dd

VolumeCheck: true
PctVariation_Tolerance: <float>

refresh_db: false
refresh_tables: # if no tables to truncate, put: -
  -

tables:
  <table1_name>:
    columns:
      <column1_name: <type>
    on_prem: <on_prem_name>
